#Precompiled views for databaseMigration
#Fri Mar 20 18:22:12 IST 2026
/WEB-INF/plugins/mail-1.0.7/grails-app/views/_testemails/testhtml.gsp=gsp_mail__testemailstesthtml_gsp
/WEB-INF/grails-app/views/internationalCertificate/show.gsp=gsp_rotary_internationalCertificateshow_gsp
/WEB-INF/grails-app/views/error.gsp=gsp_rotaryerror_gsp
/WEB-INF/grails-app/views/internationalCertificate/paymentPage.gsp=gsp_rotary_internationalCertificatepaymentPage_gsp
/WEB-INF/grails-app/views/downloadCertificate/_form.gsp=gsp_rotary_downloadCertificate_form_gsp
/WEB-INF/grails-app/views/downloadCertificate/create.gsp=gsp_rotary_downloadCertificatecreate_gsp
/WEB-INF/grails-app/views/internationalCertificate/thankyou.gsp=gsp_rotary_internationalCertificatethankyou_gsp
/WEB-INF/grails-app/views/register/index.gsp=gsp_rotary_registerindex_gsp
/WEB-INF/plugins/database-migration-1.4.0/grails-app/views/dbdoc/_stylesheet.gsp=gsp_databaseMigration_dbdoc_stylesheet_gsp
/WEB-INF/grails-app/views/superadmin/_adminFORM.gsp=gsp_rotary_superadmin_adminFORM_gsp
/WEB-INF/grails-app/views/downloadCertificate/edit.gsp=gsp_rotary_downloadCertificateedit_gsp
/WEB-INF/grails-app/views/downloadCertificate/index.gsp=gsp_rotary_downloadCertificateindex_gsp
/WEB-INF/plugins/mail-1.0.7/grails-app/views/_testemails/test.gsp=gsp_mail__testemailstest_gsp
/WEB-INF/grails-app/views/header/_logo.gsp=gsp_rotary_header_logo_gsp
/WEB-INF/grails-app/views/downloadCertificate/thankyou.gsp=gsp_rotary_downloadCertificatethankyou_gsp
/WEB-INF/grails-app/views/internationalCertificate/create.gsp=gsp_rotary_internationalCertificatecreate_gsp
/WEB-INF/plugins/mail-1.0.7/grails-app/views/_testemails/i18ntest.gsp=gsp_mail__testemailsi18ntest_gsp
/WEB-INF/grails-app/views/downloadCertificate/errorPage.gsp=gsp_rotary_downloadCertificateerrorPage_gsp
/WEB-INF/grails-app/views/mainPage/index.gsp=gsp_rotary_mainPageindex_gsp
/WEB-INF/grails-app/views/usercreate/_userFORM.gsp=gsp_rotary_usercreate_userFORM_gsp
/WEB-INF/grails-app/views/login/denied.gsp=gsp_rotary_logindenied_gsp
/WEB-INF/grails-app/views/layouts/main.gsp=gsp_rotary_layoutsmain_gsp
/WEB-INF/grails-app/views/superadmin/index.gsp=gsp_rotary_superadminindex_gsp
/WEB-INF/grails-app/views/commanUsers/index.gsp=gsp_rotary_commanUsersindex_gsp
/WEB-INF/grails-app/views/internationalCertificate/_form.gsp=gsp_rotary_internationalCertificate_form_gsp
/WEB-INF/grails-app/views/header/_topBar.gsp=gsp_rotary_header_topBar_gsp
/WEB-INF/plugins/database-migration-1.4.0/grails-app/views/dbdoc/_globalnav.gsp=gsp_databaseMigration_dbdoc_globalnav_gsp
/WEB-INF/grails-app/views/internationalCertificate/errorPage.gsp=gsp_rotary_internationalCertificateerrorPage_gsp
/WEB-INF/plugins/spring-security-core-2.0-RC5/grails-app/views/login/auth.gsp=gsp_springSecurityCore_loginauth_gsp
/WEB-INF/grails-app/views/index.gsp=gsp_rotaryindex_gsp
/WEB-INF/plugins/mail-1.0.7/grails-app/views/_testemails/tagtest.gsp=gsp_mail__testemailstagtest_gsp
/WEB-INF/plugins/database-migration-1.4.0/grails-app/views/dbdoc/_index.gsp=gsp_databaseMigration_dbdoc_index_gsp
/WEB-INF/grails-app/views/mainPage/dashboard.gsp=gsp_rotary_mainPagedashboard_gsp
/WEB-INF/grails-app/views/internationalCertificate/adminindex.gsp=gsp_rotary_internationalCertificateadminindex_gsp
/WEB-INF/grails-app/views/internationalCertificate/edit.gsp=gsp_rotary_internationalCertificateedit_gsp
/WEB-INF/grails-app/views/downloadCertificate/show.gsp=gsp_rotary_downloadCertificateshow_gsp
/WEB-INF/grails-app/views/internationalCertificate/index.gsp=gsp_rotary_internationalCertificateindex_gsp
/WEB-INF/grails-app/views/internationalCertificate/report.gsp=gsp_rotary_internationalCertificatereport_gsp
/WEB-INF/grails-app/views/superadmin/indexx.gsp=gsp_rotary_superadminindexx_gsp
/WEB-INF/grails-app/views/header/_footer.gsp=gsp_rotary_header_footer_gsp
/WEB-INF/grails-app/views/login/auth.gsp=gsp_rotary_loginauth_gsp
/WEB-INF/grails-app/views/usercreate/index.gsp=gsp_rotary_usercreateindex_gsp
/WEB-INF/grails-app/views/testmail/registration_successs.gsp=gsp_rotary_testmailregistration_successs_gsp
/WEB-INF/grails-app/views/header/_leftSide.gsp=gsp_rotary_header_leftSide_gsp
/WEB-INF/plugins/database-migration-1.4.0/grails-app/views/dbdoc/_overview-summary.gsp=gsp_databaseMigration_dbdoc_overview_summary_gsp
/WEB-INF/plugins/spring-security-core-2.0-RC5/grails-app/views/login/denied.gsp=gsp_springSecurityCore_logindenied_gsp
/WEB-INF/grails-app/views/superadmin/dashboard.gsp=gsp_rotary_superadmindashboard_gsp
/WEB-INF/grails-app/views/commanUsers/_adminFORM.gsp=gsp_rotary_commanUsers_adminFORM_gsp
